services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ${HOME}/homeflix/radarr/config:/config
      - media:/data/media
      - torrents:/data/torrents
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ${HOME}/homeflix/sonarr/config:/config
      - media:/data/media
      - torrents:/data/torrents
    ports:
      - 8989:8989
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ${HOME}/homeflix/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - WEBUI_PORT=8080
    volumes:
      - ${HOME}/homeflix/qbittorrent/config:/config
      - torrents:/data/torrents
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ${HOME}/homeflix/bazarr/config:/config
      - media:/data/media
    ports:
      - 6767:6767
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - ${HOME}/homeflix/jellyfin/cache:/cache
      - ${HOME}/homeflix/jellyfin/config:/config
      - media:/data/media
    ports:
      - 8096:8096
      - 8092:8092
      - 7359:7359/udp
      - 1900:1900/udp
    restart: unless-stopped

volumes:
  media:
    driver: local
    driver_opts:
      type: ext4
      device: /mnt/hdd/data/media
      o: bind

  torrents:
    driver: local
    driver_opts:
      type: ext4
      device: /mnt/hdd/data/torrents
      o: bind
